//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicinaPrepagada.Models.DBMedicinaPrepagada.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class Condiciones
    {
        public int id_condicion { get; set; }
        public int id_servicio { get; set; }
        public int edad_minima { get; set; }
        public int edad_maxima { get; set; }
        public int dias_afiliacion { get; set; }
        public int cantidad_maxima_servicios { get; set; }
        public string genero { get; set; }
    
        public virtual Servicios Servicios { get; set; }
    }
}
