
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MedicinaPrepagada.Models.DBMedicinaPrepagada.Source
{

using System;
    using System.Collections.Generic;
    
public partial class CuentasXPagar
{

    public int id_cuenta { get; set; }

    public int id_ips { get; set; }

    public System.DateTime fecha_periodo_ini { get; set; }

    public System.DateTime fecha_periodo_fin { get; set; }

    public double valor_a_pagar { get; set; }

    public string estado { get; set; }

    public int pagado { get; set; }



    public virtual IPS IPS { get; set; }

}

}
