

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MedicinaPrepagada.Models.DBMedicinaPrepagada.Source
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class DBPrepagadaEntities : DbContext
{
    public DBPrepagadaEntities()
        : base("name=DBPrepagadaEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<IPS> IPS { get; set; }

    public virtual DbSet<Beneficiarios> Beneficiarios { get; set; }

    public virtual DbSet<Condiciones> Condiciones { get; set; }

    public virtual DbSet<Facturas> Facturas { get; set; }

    public virtual DbSet<Facturas_Beneficiarios> Facturas_Beneficiarios { get; set; }

    public virtual DbSet<Membresias> Membresias { get; set; }

    public virtual DbSet<Negociaciones> Negociaciones { get; set; }

    public virtual DbSet<Ordenes> Ordenes { get; set; }

    public virtual DbSet<Pacientes> Pacientes { get; set; }

    public virtual DbSet<Servicios> Servicios { get; set; }

    public virtual DbSet<Titulares> Titulares { get; set; }

    public virtual DbSet<Bancos> Bancos { get; set; }

    public virtual DbSet<Contacts> Contacts { get; set; }

    public virtual DbSet<CuentasXPagar> CuentasXPagar { get; set; }

}

}

