//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicinaPrepagada.Models.DBMedicinaPrepagada.Source
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBPrepagadaEntities : DbContext
    {
        public DBPrepagadaEntities()
            : base("name=DBPrepagadaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IPS> IPS { get; set; }
        public virtual DbSet<Beneficiarios> Beneficiarios { get; set; }
        public virtual DbSet<Condiciones> Condiciones { get; set; }
        public virtual DbSet<Facturas> Facturas { get; set; }
        public virtual DbSet<Facturas_Beneficiarios> Facturas_Beneficiarios { get; set; }
        public virtual DbSet<Membresias> Membresias { get; set; }
        public virtual DbSet<Negociaciones> Negociaciones { get; set; }
        public virtual DbSet<Ordenes> Ordenes { get; set; }
        public virtual DbSet<Pacientes> Pacientes { get; set; }
        public virtual DbSet<Servicios> Servicios { get; set; }
        public virtual DbSet<Titulares> Titulares { get; set; }
    }
}
