//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicinaPrepagada.Models.DBMedicinaPrepagada.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas_Beneficiarios
    {
        public int id_factura_beneficiario { get; set; }
        public int id_beneficiario { get; set; }
        public double valor_a_pagar { get; set; }
        public int id_factura { get; set; }
        public int id_membresia { get; set; }
    
        public virtual Beneficiarios Beneficiarios { get; set; }
        public virtual Facturas Facturas { get; set; }
        public virtual Membresias Membresias { get; set; }
    }
}
