
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MedicinaPrepagada.Models.DBMedicinaPrepagada.Source
{

using System;
    using System.Collections.Generic;
    
public partial class Facturas
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Facturas()
    {

        this.Facturas_Beneficiarios = new HashSet<Facturas_Beneficiarios>();

    }


    public int id_factura { get; set; }

    public int id_titular { get; set; }

    public System.DateTime fecha_factura { get; set; }

    public System.DateTime fecha_factura_inicio { get; set; }

    public System.DateTime fecha_factura_fin { get; set; }

    public System.DateTime fecha_cancelado { get; set; }

    public double valor_a_pagar { get; set; }

    public string estado { get; set; }

    public double pagado { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Facturas_Beneficiarios> Facturas_Beneficiarios { get; set; }

    public virtual Titulares Titulares { get; set; }

}

}
