
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MedicinaPrepagada.Models.DBMedicinaPrepagada.Source
{

using System;
    using System.Collections.Generic;
    
public partial class Facturas_Beneficiarios
{

    public int id_factura_beneficiario { get; set; }

    public int id_beneficiario { get; set; }

    public double valor_a_pagar { get; set; }

    public int id_factura { get; set; }

    public int id_membresia { get; set; }



    public virtual Beneficiarios Beneficiarios { get; set; }

    public virtual Facturas Facturas { get; set; }

    public virtual Membresias Membresias { get; set; }

}

}
