//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicinaPrepagada.Models.DBMedicinaPrepagada.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facturas()
        {
            this.Facturas_Beneficiarios = new HashSet<Facturas_Beneficiarios>();
        }
    
        public int id_factura { get; set; }
        public int id_titular { get; set; }
        public System.DateTime fecha_factura { get; set; }
        public System.DateTime fecha_factura_inicio { get; set; }
        public System.DateTime fecha_factura_fin { get; set; }
        public System.DateTime fecha_cancelado { get; set; }
        public double valor_a_pagar { get; set; }
        public string estado { get; set; }
        public double pagado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas_Beneficiarios> Facturas_Beneficiarios { get; set; }
        public virtual Titulares Titulares { get; set; }
    }
}
