//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicinaPrepagada.Models.DBMedicinaPrepagada.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPS
    {
        public int id_ips { get; set; }
        public string nombre { get; set; }
        public string nit { get; set; }
        public string telefono { get; set; }
        public string nombre_contacto { get; set; }
        public string apellidos_contacto { get; set; }
        public bool transferencia { get; set; }
        public string numero_cuenta { get; set; }
    }
}
