
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MedicinaPrepagada.Models.DBMedicinaPrepagada.Source
{

using System;
    using System.Collections.Generic;
    
public partial class IPS
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public IPS()
    {

        this.Negociaciones = new HashSet<Negociaciones>();

        this.Ordenes = new HashSet<Ordenes>();

        this.CuentasXPagar = new HashSet<CuentasXPagar>();

    }


    public int id_ips { get; set; }

    public string nombre { get; set; }

    public string nit { get; set; }

    public string telefono { get; set; }

    public string nombre_contacto { get; set; }

    public string apellidos_contacto { get; set; }

    public bool transferencia { get; set; }

    public string numero_cuenta { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Negociaciones> Negociaciones { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Ordenes> Ordenes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CuentasXPagar> CuentasXPagar { get; set; }

}

}
