//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicinaPrepagada.Models.DBMedicinaPrepagada.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class Negociaciones
    {
        public int id_negociacion { get; set; }
        public int id_servicio { get; set; }
        public int id_ips { get; set; }
        public double valor { get; set; }
        public bool habilitado { get; set; }
    
        public virtual IPS IPS { get; set; }
        public virtual Servicios Servicios { get; set; }
    }
}
