//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicinaPrepagada.Models.DBMedicinaPrepagada.Source
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordenes
    {
        public int id_orden { get; set; }
        public int id_paciente { get; set; }
        public int id_servicio { get; set; }
        public int id_ips { get; set; }
        public int id_membresia { get; set; }
        public System.DateTime fecha_solicitud { get; set; }
        public double valor_copago { get; set; }
        public double valor_cuota_moderadora { get; set; }
        public string estado { get; set; }
    
        public virtual IPS IPS { get; set; }
        public virtual Membresias Membresias { get; set; }
        public virtual Pacientes Pacientes { get; set; }
        public virtual Servicios Servicios { get; set; }
    }
}
