
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MedicinaPrepagada.Models.DBMedicinaPrepagada.Source
{

using System;
    using System.Collections.Generic;
    
public partial class Pacientes
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Pacientes()
    {

        this.Beneficiarios = new HashSet<Beneficiarios>();

        this.Ordenes = new HashSet<Ordenes>();

        this.Titulares = new HashSet<Titulares>();

    }


    public int id_paciente { get; set; }

    public string nombre { get; set; }

    public string apellidos { get; set; }

    public string documento { get; set; }

    public System.DateTime fecha_nacimiento { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Beneficiarios> Beneficiarios { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Ordenes> Ordenes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Titulares> Titulares { get; set; }

}

}
